quarkus.http.port=8081
quarkus.s3.devservices.enabled=false
#TODO: Shift to env file later
quarkus.s3.endpoint-override=http://localhost:9000
quarkus.s3.aws.region=us-east-1
quarkus.s3.aws.credentials.type=static
quarkus.s3.aws.credentials.static-provider.access-key-id=admin
quarkus.s3.aws.credentials.static-provider.secret-access-key=password

bucket.name=warehouse